sudo: false
language: cpp

## notifications
notifications:
   email: off

## whitelist
#branches:
#  only:
#      - build-ci

## whitelist - end

compiler:
  - g++

addons:
   apt:
     packages:
      - g++
      - reprepro
      - devscripts
      - coreutils
      - guile-1.8-libs
      - xorg-dev
      
  
# before_install:

# install:

# before_script:

#script:
#     - ./configure
#     - make
     
after_failure:
   - cat configure.log


# after_success:

## optional
# before_deploy:

## optional
# deploy:

## optional
# after_deploy:

# after_script:




##### END OF FILE #####
